// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Zo2t2hUQ5HYyQjQzljGQq75z9ef36P4',
    appId: '1:632398070502:web:8cc4f4920628785e37f127',
    messagingSenderId: '632398070502',
    projectId: 'fixmate-fab73',
    authDomain: 'fixmate-fab73.firebaseapp.com',
    storageBucket: 'fixmate-fab73.firebasestorage.app',
    measurementId: 'G-E5KKSC0V1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB79IMPB1Sakai2eQNStvqR7_lbM6YU4ZY',
    appId: '1:632398070502:android:c0c18c59608e3ede37f127',
    messagingSenderId: '632398070502',
    projectId: 'fixmate-fab73',
    storageBucket: 'fixmate-fab73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_tS2BfeeEbrVzNG1AyqvkPcga-5vCdno',
    appId: '1:632398070502:ios:463e8f15ebc75fef37f127',
    messagingSenderId: '632398070502',
    projectId: 'fixmate-fab73',
    storageBucket: 'fixmate-fab73.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_tS2BfeeEbrVzNG1AyqvkPcga-5vCdno',
    appId: '1:632398070502:ios:463e8f15ebc75fef37f127',
    messagingSenderId: '632398070502',
    projectId: 'fixmate-fab73',
    storageBucket: 'fixmate-fab73.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Zo2t2hUQ5HYyQjQzljGQq75z9ef36P4',
    appId: '1:632398070502:web:7e57c9a533d2bff737f127',
    messagingSenderId: '632398070502',
    projectId: 'fixmate-fab73',
    authDomain: 'fixmate-fab73.firebaseapp.com',
    storageBucket: 'fixmate-fab73.firebasestorage.app',
    measurementId: 'G-FYLHT49X9L',
  );
}
